const zhLang = {
  restartApp: '加载失败，请重新启动小程序',
  cancel: '取消',
  share: '分享',
  shareFriend: '分享给朋友',
  generateCard: '生成卡片 保存分享',
  copyLink: '复制产品链接',
  upvote: '点赞',
  upvoted: '已赞',
  forNow: '目前就这些了。',
  later: '过会儿再来看看吧~🐱',
  loading: '加载中',
  day: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  month: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
}
const enLang = {
  restartApp: 'Launch failed, please restart mini app',
  cancel: 'Cancel',
  share: 'SHARE',
  shareFriend: 'Share to friends',
  generateCard: 'Generate QRCode card',
  copyLink: 'Copy product link',
  upvote: 'UPVOTE',
  upvoted: 'UPVOTED',
  forNow: "That's all for now.",
  later: 'Come later and pulldown to refresh ~ 🐱',
  loading: 'Loading',
  day: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  ],
  month: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'Auguest',
    'September',
    'October',
    'November',
    'December',
  ],
}

export const langs = {
  zh: zhLang,
  zh_CN: zhLang,
  en: enLang,
  en_US: enLang,
}
